### ISSUE TITLE
Compile takes fuzzy strings

### ISSUE THREAD

**Issue by intellix** [rubenv/grunt-angular-gettext#34]
Hey, I've not seen any mention of this issue yet which confuses me a little, but it seems like when I run compile on a PO > JSON, I end up with the fuzzy strings as well which are suggested and absolutely insane suggestions at that, causing 1 word strings to be suggested with a paragraph of text.

**Comment by gsouf** [comment]
Thumb up, fuzzy string might want to be included. In our case it's a marker added automatically by the localization platform for any strings that are not reviewed. Does not mean they are bad

**Comment by gsouf** [comment]
Found the undocumented option ignoreFuzzyString:

		options: {
		  format: "json",
			ignoreFuzzyString: false
		},
