### ISSUE TITLE
Display line number beside filename when extracting

### ISSUE THREAD

**Issue by mbuttu** [rubenv/grunt-angular-gettext#39]
Hi @rubenv, is it possible to provide an option to show the line number beside the filename in the outputted ```.pot``` file while extracting?

For example, this is what is currently output:
```
#: /absolute/path
msgid "Welcome!"
msgstr ""
```

And this is what I'm trying to achieve:

```
#: /absolute/path:588
msgid "Welcome!"
msgstr ""
```
Notice the colon and the line number after the path to the file.

Thanks!

**Comment by gabegorelick** [comment]
This is possible since angular-gettext-tools v2.0. If you upgrade grunt-angular-gettext to the latest version you should start seeing line numbers in JS and HTML. 

https://github.com/rubenv/angular-gettext-tools/pull/59
https://github.com/rubenv/angular-gettext-tools/pull/49
