### ISSUE TITLE
Custom annotation for extracting strings in Javascript files

### ISSUE THREAD

**Issue by kudlajz** [rubenv/grunt-angular-gettext#43]
Your documentation states, that to get translated strings in Javascript files, you have to mark it like this
```
gettextCatalog.getString('asdf');
```
however, if I have a wrapper service called **Translate** with a function **get(string)** that internally calls method above, these strings are not extracted.

Is there a way to include custom expression to match my function calls instead of yours?

Thank you.

**Comment by gabegorelick** [comment]
This is indeed supported via the `markerName` option, although it may not be documented as much as it should. You can see an example in the tests: https://github.com/rubenv/angular-gettext-tools/blob/2f283e62c2685f71414994c0a01d5709d7bd64cb/test/extract.js#L229
