### ISSUE TITLE
Extract ternary binding.

### ISSUE THREAD

**Issue by Jeff-Cortese** [rubenv/grunt-angular-gettext#45]
I often write bindings for static text that are based on some condition like this...
````html
<span>
  {{ myCtrl.isEnabled ? 'Enabled' : 'Disabled' | translate }}
</span>
````
...but the extractor does not pick up `'Enabled'` or `'Disabled'`.

There are certainly workarounds to this that are more verbose, but I prefer how concise this binding is.

**Comment by gabegorelick** [comment]
We certainly can't support every possible way you might want to call the translate filter. When dealing with this kind of static analysis, you just have to learn to write code amenable to the tools, i.e. use the standard Angular conditionals (ng-if, ng-show, ng-hide, ng-switch, etc.) instead. It's not ideal, but that's the halting problem for you :)

I'm willing to be overruled if other people think this would be worth the cost though.

**Comment by Jeff-Cortese** [comment]
I understand. Thanks for your consideration.
