### ISSUE TITLE
Bug/Change Request: Only one extracted node for different comments on same content

### ISSUE THREAD

**Issue by zarko-tg** [rubenv/grunt-angular-gettext#46]
Some index.html
```html
<span translate-comment="Translate as a verb" translate>Book</span>
<span translate-comment="Translate as a noun" translate>Book</span>
```
is extracted into:
```
#. Translate as a noun
#. Translate as a verb
#: index.html:100
#: index.html:101
msgid "Book"
msgstr “"
```
and poEdit offers only one node for translation.

Shouldn't it instead split into two different nodes?
As in:
```
#. Translate as a verb
#: index.html:100
msgid "Book"
msgstr ""

#. Translate as a noun
#: index.html:101
msgid "Book"
msgstr ""
```

**Comment by rubenv** [comment]
Current behaviour is exactly as it should be.

You should use contexts:
```
<span translate-context="verb" translate>Book</span>
<span translate-context="noun" translate>Book</span>
```

**Comment by zarko-tg** [comment]
Cheers!
Maybe clarify under Comment section in https://angular-gettext.rocketeer.be/dev-guide/annotate/
regarding the difference between "comment" and "context"? And what values are allowed for translate-context.

**Comment by rubenv** [comment]
Happy to help!

Documenting contexts is on the TODO, but I haven't gotten round to it: https://github.com/rubenv/angular-gettext-website/issues/4

**Comment by zarko-tg** [comment]
Alrighty then. Feel free to close this issue.
