### ISSUE TITLE
Translating complex angular binding

### ISSUE THREAD

**Issue by AkosLukacs** [rubenv/grunt-angular-gettext#47]
Hi!

This is more of a how-to question, maybe you know how to solve this: I want to translate an angular binding that has conditional logic like this (it's a create/edit form): ```<h3>{{stuff.id ? 'Edit stuff' : 'Create new stuff'}}</h3>```

The grunt task doesn't pick up the translate filter in the conditional binding, so if I'm writing this ```<h3>{{stuff.id ? ('Edit stuff'|translate) : ('Create new stuff'|translate)}}</h3>```, "edit stuff" and "create new stuff" won't get into the generated .pot file.

The translation itself does work, if I manually add the translation, but do you know how could I avoid the manual step?

**Comment by rubenv** [comment]
We do this:

```html
<h3 ng-if="stuff.id" translate>Edit stuff</h3>
<h3 ng-if="!stuff.id" translate>Create new stuff</h3>
```

**Comment by AkosLukacs** [comment]
That was my first idea too :) 
Thanks.
