### ISSUE TITLE
Option for not including line numbers / filename in .pot file (enhancement)

### ISSUE THREAD

**Issue by AntonTrapp** [rubenv/grunt-angular-gettext#51]
_What is happening?_
When generating one big .js file out of many .coffee (or whatever) files in grunt the filename will always be the same and the all line numbers are changing all the time. Not funny for version management.

_Possible solution?_
Option to include/exclude filename and/or line number. The other way would be to generate the .pot out of the .coffee / whatever sources ;)

Would be the opposite of #39 ;)

**Comment by gabegorelick** [comment]
FYI, if you're concerned about diffs, you probably shouldn't be updating
your POT files that much. Translation is inherently a waterfall process,
unfortunately, so you really only need to to regenerate your POT after
"string freeze." Of course every team has a different process, but that's
typically how it works.

**Comment by AntonTrapp** [comment]
Problem here is, that we make the first translation during development. In most other cases: no problem, you are right there!

**Comment by gabegorelick** [comment]
If you still want this implemented, open it against rubenv/angular-gettext-tools. The grunt plugin is just a frontend for that.
