### ISSUE TITLE
Example: Semi-Automatically Translate PO(T) File With Google Translator Kit

### ISSUE THREAD

**Issue by xErik** [rubenv/grunt-angular-gettext#52]
I figured out a (rather tedious) way to translate a PO(T) file using the Google Translator Kit, while respecting the Angular environment. This could be interesting info for your homepage.

**Remarks**

1. Google accepts PO files, only.
2. Google accepts `<tags>var</tags>` as placeholders, only.

The code below takes this into account.

**Process**

1. `gulp pot.google`
2. Upload `po/template.po` to https://translate.google.com/toolkit/docupload?hl=en
(Set the file name online to your target language e.g., `nl.po`)
3. Click on:  `No, thanks. I'll translate myself or invite friends for help.`
4. Translate online. 
5. Choose `File > Save and Close`
6. Click checkbox of file and download file via top menu.
7. Use Poedit to set the language of downloaded file under: Catalaog > Properties ...
8. `gulp translate.google` (ignores `po/template.po` which is in truth a POT file)

**Related Gulp Tasks**

```javascript
var gettext = require('gulp-angular-gettext');
var replace = require('gulp-replace');

gulp.task('pot.google', function () {
    return gulp.src(['./node_modules/drm*/**/src/*.html'])
        .pipe(gettext.extract('template.po', { // google accepts PO files, ony!
            // options
        }))
        .pipe(replace(/\{\{/g, '<interpolate>')) // google uses <tags>count</tags> as placeholders
        .pipe(replace(/\}\}/g, '</interpolate>'))
        .pipe(gulp.dest('po/'));
});

gulp.task('translate.google', function () {
    return gulp.src(['po/**/*.po', '!po/template.po']) // Ignoring template.po, which in truth is a POT file
        .pipe(gettext.compile({
            format: 'json'
        }))
        .pipe(replace(/<interpolate>\s*/g, '{{')) // Remove the whitespace google adds
        .pipe(replace(/\s*<\/\s+interpolate>/g, '}}')) // Remove the whitespace google adds
        .pipe(gulp.dest('po/'));
});
```

**Example**

_Input: PO(T) generated by `gulp pot.google`_

```
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Project-Id-Version: \n"

#: drm-site-component-expert/src/expertView.html:33
msgid "I saw <interpolate>count</interpolate> unicorns!"
msgstr ""

#: drm-site-component-expert/src/expertView.html:47
msgid "PDF"
msgstr ""

#: drm-site-component-expert/src/expertView.html:46
msgid "Print"
msgstr ""

#: drm-site-component-expert/src/expertView.html:45
msgid "Reset"
msgstr ""
```

_Output: JSON generated by `gulp translate.google`_

```json
{"nl":{"I saw {{count</interpolate> unicorns!":"Ik zag {{count}} eenhoorns!","PDF":"PDF","Print":"Afdruk","Reset":"Reset"}}
```

**TODO**

Check out if plural forms are working correctly.

**Comment by gabegorelick** [comment]
Thanks for documenting this. I'm not really a fan of serving machine translation to your users since all browsers nowadays will do it for the users, but with a better UX IMHO (since users opt-in to the machine translation, it's not as annoying to them when it's bad). Anyway, feel free to continue to post here with what you discover.
