### ISSUE TITLE
Extract strings from CoffeeScript

### ISSUE THREAD

**Issue by elimence** [rubenv/grunt-angular-gettext#55]
When I started using this, I assumed it worked for both .js and .coffee files, but I'm unable to get it to work with .coffee files. There's no mention of such a limitation on the site too. I'm I missing something? or do I need to do something extra to get strings extracted from .coffee files ?

**Comment by rubenv** [comment]
Convert your CoffeeScript to JS first, then extract from the JS.

You'll need to convert to JS anyway, so this won't be extra work.

**Comment by elimence** [comment]
Alright thanks, I'll do that then.

**Comment by rubenv** [comment]
We decided to do it this way because there are tons of languages that need extraction, but in the end they all need to compile to JavaScript. If we were to add direct support for CoffeeScript etc (which I also used initially), the dependencies to grunt-angular-gettext would become enormous.

**Comment by elimence** [comment]
I totally agree. At first, I assumed the text extraction was done by parsing files and using regex to isolate strings marked for translation, which is why I expected it to work for coffeescript as well.
I'll comb through the code to see how it's done.
It's a great service by the way, makes life really easy, I'm currently migrating from angular translate.
